// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("assessment_questions")]
    public partial class AssessmentQuestion
    {
        public AssessmentQuestion()
        {
            AssessmentAnswers = new HashSet<AssessmentAnswer>();
            AssessmentMatches = new HashSet<AssessmentMatch>();
            AssessmentOptions = new HashSet<AssessmentOption>();
            AssessmentQuestionsRelations = new HashSet<AssessmentQuestionsRelation>();
            AssessmentTexts = new HashSet<AssessmentText>();
            AssessmentTrueFalses = new HashSet<AssessmentTrueFalse>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("question", TypeName = "text")]
        public string Question { get; set; }
        [Column("category_id")]
        public long CategoryId { get; set; }
        [Column("level")]
        public int Level { get; set; }
        [Column("order")]
        public int Order { get; set; }
        [Column("type", TypeName = "text")]
        public string Type { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [InverseProperty("Question")]
        public virtual ICollection<AssessmentAnswer> AssessmentAnswers { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<AssessmentMatch> AssessmentMatches { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<AssessmentOption> AssessmentOptions { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<AssessmentQuestionsRelation> AssessmentQuestionsRelations { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<AssessmentText> AssessmentTexts { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<AssessmentTrueFalse> AssessmentTrueFalses { get; set; }
    }
}