// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("assessment_true_false")]
    public partial class AssessmentTrueFalse
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("question_id")]
        public long QuestionId { get; set; }
        [Column("is_true")]
        public int IsTrue { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [ForeignKey("QuestionId")]
        [InverseProperty("AssessmentTrueFalses")]
        public virtual AssessmentQuestion Question { get; set; }
    }
}