// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("assessment_questions_relation")]
    public partial class AssessmentQuestionsRelation
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("question_id")]
        public long QuestionId { get; set; }
        [Column("assessment_id")]
        public long AssessmentId { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [ForeignKey("AssessmentId")]
        [InverseProperty("AssessmentQuestionsRelations")]
        public virtual Assessment Assessment { get; set; }
        [ForeignKey("QuestionId")]
        [InverseProperty("AssessmentQuestionsRelations")]
        public virtual AssessmentQuestion Question { get; set; }
    }
}