// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("assessment_match")]
    [Microsoft.EntityFrameworkCore.Index("AnswerIdKey", Name = "IX_assessment_match", IsUnique = true)]
    [Microsoft.EntityFrameworkCore.Index("QuestionIdKey", Name = "IX_assessment_match_1", IsUnique = true)]
    public partial class AssessmentMatch
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("answer_id_key")]
        [StringLength(36)]
        [Unicode(false)]
        public string AnswerIdKey { get; set; }
        [Required]
        [Column("question_id_key")]
        [StringLength(36)]
        [Unicode(false)]
        public string QuestionIdKey { get; set; }
        [Column("option", TypeName = "text")]
        public string Option { get; set; }
        [Column("answer", TypeName = "text")]
        public string Answer { get; set; }
        [Column("question_id")]
        public long QuestionId { get; set; }
        [Column("order")]
        public int Order { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [ForeignKey("QuestionId")]
        [InverseProperty("AssessmentMatches")]
        public virtual AssessmentQuestion Question { get; set; }
    }
}