// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context_Layer.Models
{
    [Table("assessments")]
    public partial class Assessment
    {
        public Assessment()
        {
            AssessmentAnswers = new HashSet<AssessmentAnswer>();
            AssessmentData = new HashSet<AssessmentDatum>();
            AssessmentDepartments = new HashSet<AssessmentDepartment>();
            AssessmentEnrols = new HashSet<AssessmentEnrol>();
            AssessmentMeta = new HashSet<AssessmentMetum>();
            AssessmentQuestionsRelations = new HashSet<AssessmentQuestionsRelation>();
            AssessmentSections = new HashSet<AssessmentSection>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("title")]
        [StringLength(255)]
        [Unicode(false)]
        public string Title { get; set; }
        [Column("short_description", TypeName = "text")]
        public string ShortDescription { get; set; }
        [Column("description", TypeName = "text")]
        public string Description { get; set; }
        [Column("slug")]
        [StringLength(255)]
        [Unicode(false)]
        public string Slug { get; set; }
        [Column("created_by")]
        public int? CreatedBy { get; set; }
        [Column("updated_by")]
        public int? UpdatedBy { get; set; }
        [Column("duration")]
        public int Duration { get; set; }
        [Column("category_id")]
        public long? CategoryId { get; set; }
        [Column("thumbnail")]
        [StringLength(255)]
        [Unicode(false)]
        public string Thumbnail { get; set; }
        [Column("published")]
        public byte Published { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentAnswer> AssessmentAnswers { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentDatum> AssessmentData { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentDepartment> AssessmentDepartments { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentEnrol> AssessmentEnrols { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentMetum> AssessmentMeta { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentQuestionsRelation> AssessmentQuestionsRelations { get; set; }
        [InverseProperty("Assessment")]
        public virtual ICollection<AssessmentSection> AssessmentSections { get; set; }
    }
}